game:
  arch: win64
  args: -opengl -SkipBuildPatchPrereq
  exe: drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe
  prefix: /home/emile/Games/epic-games-store
system:
  env:
    DXVK_HUB: fps
    DXVK_HUD: compiler
    MESA_GL_VERSION_OVERRIDE: 4.4COMPAT
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/emile/Games/epic-games-store
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP: '1'
  gamemode: true
wine:
  Desktop: false
  dxvk: true
  esync: true
  fsync: true
  show_debug: +fps
  system_winetricks: false
  version: lutris-5.7-x86_64
  vkd3d: true
  x360ce-dinput: false
  x360ce-xinput9: false
